### ISSUE TITLE
Add records support for base classes in GenericRepository

### ISSUE THREAD

**Issue by hardcoder** [SimplifyNet/Simplify#237]
**Is your feature request related to a problem? Please describe.**
Could not inherit record type from class.

**Describe the solution you'd like**
For example, inherit CustomRecord from IdentityRecord.

**Describe alternatives you've considered**
Just a new record type, delivered with C# 9.0.

**Additional context**
--

**Comment by hardcoder** [comment]
Inheriting from record in nuget-package works well. Checked by creating test package [Nucleus](https://www.nuget.org/packages/Nucleus/1.1.0-a1) contaning ExampleRecord type. Record type inheritance works as expected in projects targeting .NET Framework 4.8 / .NET Core 3.1 / .NET 5.0. ([Test project](https://github.com/hardcoder/nucleus))

**Comment by i4004** [comment]
Pre-release packages for test has been created: https://www.nuget.org/packages/Simplify.Repository.FluentNHibernate/1.3.0-pre01

**Comment by hardcoder** [comment]
FluentNHibernate throws **NHibernate.InvalidProxyTypeException**:
_The following types may not be used as proxies:
{TypeFullName here}: method Equals should be 'public/protected virtual' or 'protected internal virtual'_

**Comment by i4004** [comment]
Can't be done in NHibernate.
To prevent object change ReadOnly option can be used: https://stackoverflow.com/a/2871277/550882
