### ISSUE TITLE
Corrupted Simplify Your Web extensions library - Please re-install

### ISSUE THREAD

**Issue by kiki-G** [SimplifyNet/Simplify#477]
Hi there, After migration to Joomla 4.3.1 I got an error “Corrupted Simplify Your Web extensions library - Please re-install”. I try to re-install many times but unfortunately no success. I’m not sure how to solve it. Any ideas out there are welcomed! Thanks in advance

**Comment by i4004** [comment]
Hi! Joomla is a PHP-based platform. This repository is about .NET libraries.
